name: abenceapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# CAMBIO IMPORTANTE: Subimos la versión visible (1.0.1) y el código de compilación (+2)
version: 1.0.3+4

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  intl: ^0.20.2
  flutter_datetime_picker_plus: ^2.2.0
  firebase_storage: ^13.0.4
  image_picker: ^1.2.1
  file_picker: ^10.3.6
  flutter_cached_pdfview: ^0.4.3
  excel: ^4.0.6
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  url_launcher: ^6.3.2
  upgrader: ^12.3.0
  version: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

# CONFIGURACIÓN DE ICONOS
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21 
  remove_alpha_ios: true 

# CONFIGURACIÓN DE PANTALLA DE CARGA (SPLASH)
flutter_native_splash:
  color: "#FFFFFF" 
  image: "assets/icon/logo.png"
  android_12: 
    image: "assets/icon/logo.png"
    color: "#FFFFFF"
  web: false